import { NextRequest, NextResponse } from 'next/server';
import { findRelevantContext } from '@/lib/document-processor';
import { chatCompletion } from '@/lib/openai';

export async function POST(request: NextRequest) {
  try {
    console.log('Fill section API called');
    const body = await request.json();
    const { sectionTitle, sectionContent, projectPrompt, contextualDocuments } = body;
    
    console.log('Request data:', {
      sectionTitle,
      sectionContentLength: sectionContent?.length || 0,
      projectPromptLength: projectPrompt?.length || 0,
      contextualDocsCount: contextualDocuments?.length || 0,
    });

    if (!sectionTitle || !projectPrompt) {
      return NextResponse.json(
        { error: 'Section title and project prompt are required' },
        { status: 400 }
      );
    }

    // Combine knowledge base context with contextual documents if provided
    console.log('Finding relevant context from knowledge base...');
    let context = await findRelevantContext(`${sectionTitle} ${projectPrompt}`, 10);
    console.log('Context found, length:', context.length);
    
    if (contextualDocuments && contextualDocuments.length > 0) {
      const contextualText = contextualDocuments
        .map((doc: { content: string; name: string }) => `[${doc.name}]:\n${doc.content}`)
        .join('\n\n---\n\n');
      context = `${context}\n\nAdditional Context from Uploaded Documents:\n${contextualText}`;
    }

    // Generate content for this section
    const fillPrompt = `Fill in the following section of a project management document.

Section Title: ${sectionTitle}
Current Section Content: ${sectionContent || '(empty)'}

Project Description:
${projectPrompt}

Knowledge Base Context:
${context}

Generate appropriate content for this section that:
- Aligns with the project description
- Is specific, professional, and relevant
- Fits naturally into a project management document
- Maintains consistency with the section title/heading
- Is comprehensive but concise
- Avoids markdown formatting like **bold** or *italic*.
- Uses colons (:) instead of double hyphens (--) for lists or separations.
- Does NOT include phrases like "AI generated content" or "Generated content".

Return only the filled content for this section, without repeating the section title.`;

    console.log('Calling OpenAI to generate content...');
    const filledContent = await chatCompletion(
      [
        {
          role: 'system',
          content: 'You are filling in sections of a project management document. Generate content that is specific, professional, and aligned with the project goals. Avoid markdown bold/italic, use colons instead of double hyphens, and do not mention "AI generated content".',
        },
        {
          role: 'user',
          content: fillPrompt,
        },
      ],
      context,
      { temperature: 0.5, preserveSystemMessage: true }
    );

    console.log('Content generated successfully, length:', filledContent.length);

    // Clean up the content: remove **, replace -- with :, remove AI-generated mentions
    let cleanedContent = filledContent
      .replace(/\*\*/g, '') // Remove **
      .replace(/--/g, ':') // Replace -- with :
      .replace(/AI[- ]generated content/gi, '') // Remove "AI generated content" phrases
      .replace(/AI[- ]generated/gi, '') // Remove "AI-generated" phrases
      .replace(/generated by AI/gi, '') // Remove "generated by AI"
      .replace(/This content was generated/gi, '') // Remove "This content was generated"
      .trim();

    return NextResponse.json({
      success: true,
      filledContent: cleanedContent,
    });
  } catch (error) {
    console.error('❌ Section fill error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    const errorStack = error instanceof Error ? error.stack : undefined;
    console.error('Error details:', { errorMessage, errorStack });
    
    return NextResponse.json(
      { 
        error: 'Failed to fill section', 
        details: errorMessage,
        ...(process.env.NODE_ENV === 'development' && { stack: errorStack })
      },
      { status: 500 }
    );
  }
}

